### ISSUE TITLE
ERROR:root:Error parsing

### ISSUE THREAD

**Issue by yangshare** [ideamark/breadbot#2]
### ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/breadbot/.eggs/pbr-4.2.0-py3.7.egg/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/breadbot/.eggs/pbr-4.2.0-py3.7.egg/pbr/util.py", line 259, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/breadbot/.eggs/pbr-4.2.0-py3.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/breadbot/.eggs/pbr-4.2.0-py3.7.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/breadbot/.eggs/pbr-4.2.0-py3.7.egg/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/breadbot/.eggs/pbr-4.2.0-py3.7.egg/pbr/packaging.py", line 839, in get_version
    name=package_name))

### Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name breadbot was given, but was not able to be found.
error in setup command: Error parsing /home/breadbot/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name breadbot was given, but was not able to be found.

**Comment by uncle-mark** [comment]
Try "sudo pip3 install -U pbr" and see if it helps.
